@url_dev=http://localhost:3000/v1/api

# Create product
POST {{url_dev}}/product
Content-Type: application/json
x-shop-id: 668e36e79728f78446471225
x-api-key: f78a9a6f281617996a25142c14f4389bafed657743ddaa1052de567fce92b390a1c93048b8627085d7fcff02a4f5ae2672ff33e0e5e15ca8871374c895ce9c9d
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjhlMzZlNzk3MjhmNzg0NDY0NzEyMjUiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzIwNTk2MTk5LCJleHAiOjE3MjEyMDA5OTl9.kRb9PoX4Jl3aJ3K7-Mzjwm5_iS3318Xt4Yk4qlBbuEo

{
	"name": "New Jeans",
	"description": "High-quality denim jeans",
	"price": 50,
	"type": "clothing",
	"thumbnail": "thumbnail",
	"quantity": 5,
	"attributes": {
		"brand": "Levi's",
		"size": "L",
		"material": "Denim"
	}
}